export const CATEGORIES_GET_REQUEST = 'CATEGORIES_GET_REQUEST';
export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

export const SUBCATEGORIES_GET_REQUEST = 'SUBCATEGORIES_GET_REQUEST';
export const SUBCATEGORIES_GET_SUCCESS = 'SUBCATEGORIES_GET_SUCCESS';
export const SUBCATEGORIES_GET_FAILURE = 'SUBCATEGORIES_GET_FAILURE';