export const CATEGORIES_ALL_GET_REQUEST = 'CATEGORIES_ALL_GET_REQUEST';
export const CATEGORIES_ALL_GET_SUCCESS = 'CATEGORIES_ALL_GET_SUCCESS';
export const CATEGORIES_ALL_GET_FAILURE = 'CATEGORIES_ALL_GET_FAILURE';
