// export const VIDEOS_GET_REQUEST = 'VIDEOS_GET_REQUEST';
// export const VIDEOS_GET_SUCCESS = 'VIDEOS_GET_SUCCESS';
// export const VIDEOS_GET_FAILURE = 'VIDEOS_GET_FAILURE';

export const VIDEO_GET_REQUEST = 'VIDEO_GET_REQUEST';
export const VIDEO_GET_SUCCESS = 'VIDEO_GET_SUCCESS';
export const VIDEO_GET_FAILURE = 'VIDEO_GET_FAILURE';
